name: Spring-boot-helloworld-GitHub-Actions
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-helloworld-0.0.1-SNAPSHOT
          path: target/spring-boot-helloworld-0.0.1-SNAPSHOT.jar 
          retention-days: 1